version: '3.8'

services:
  blindtreasure.api:
    image: ${DOCKER_REGISTRY-}blindtreasureapi
    build:
      context: .
      dockerfile: BlindTreasure.API/Dockerfile
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=blindtreasure_db;Username=postgres;Password=postgres
    ports:
      - "5000:5000"

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: blindtreasure_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
