name: Deploy to VPS

on:
  repository_dispatch:
    types: [deploy-blindtreasure]  # Workflow này được kích hoạt khi workflow build gửi tín hiệu "deploy-blindtreasure"

jobs:
  deploy:
    runs-on: ubuntu-latest  # Máy chủ ảo của GitHub để thực hiện thao tác SSH

    steps:
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v1.0.3  # Plugin để chạy lệnh SSH từ xa vào VPS
        with:
          host: ${{ secrets.VPS_HOST }}  # IP hoặc domain của VPS (khai báo trong repo secret)
          username: ${{ secrets.VPS_USER }}  # Tên user đăng nhập (thường là root)
          password: ${{ secrets.VPS_PASSWORD }}  # SSH password để đăng nhập

          script: |
            cd /root/projects/blindtreasure  # Di chuyển đến thư mục chứa file docker-compose.yml trên VPS

            echo "Pulling latest Docker image..."
            docker compose pull  # Kéo image mới nhất từ Docker Hub

            echo "Backing up previous image tag..."
            docker image tag blindtreasureapi:latest blindtreasureapi:backup || true  # Gắn tag dự phòng để rollback nếu cần

            echo "Restarting container..."
            docker compose up -d  # Chạy hoặc restart container với image mới

            echo "Removing dangling images to save space..."
            docker image prune -f  # Xóa những image không dùng tới để tiết kiệm dung lượng ổ đĩa

            echo "Checking health status..."
            curl -f http://localhost:5000/health || echo "WARNING: Healthcheck failed"  
            # Gọi thử endpoint của API xem có chạy không, nếu lỗi thì cảnh báo nhưng không dừng workflow
