name: Deploy to VPS

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"] 
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}  
    runs-on: ubuntu-latest

    steps:
      - name: SSH vào VPS & Deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            # Đăng nhập vào DockerHub
            docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
            
            # Chuyển đến thư mục chứa docker-compose.yml
            cd /root/projects/blindtreasure  # Chắc chắn rằng bạn đang ở đúng thư mục chứa docker-compose.yml
            
            # Pull image mới từ DockerHub
            docker-compose pull
            
            # Dừng và xóa các container hiện tại
            docker-compose down
            
            # Khởi động lại containers với docker-compose
            docker-compose up -d --force-recreate
            
            # Dọn dẹp hệ thống Docker
            docker system prune -af

